config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  resources :books, only: [:edit, :create, :index, :show, :destroy, :update]
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true, Length: { maximum: 200 }

  has_one_attached :profile_image
  belongs_to :user

def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/default-image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, Length: { minimum: 2 , maximum: 20 }

  has_one_attached :profile_image
  has_many :books, dependent: :destroy

def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/default-image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end

  validates :introduction, Length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :current_user, only: [:edit, :update]

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
      if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
      else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(user_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @users = User.all
    # @users = @user.book.page(params[:page])
    @book = Book.new
  end

  def create
   @book = Book.new(book_params)
   @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id:@user)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user.id)
    else
      @users = User.all
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(user_path) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, method: :patch do |f| %><br>
  <label>Title</label><br>
  <%= f.text_field :title %><br>
  <div class="form-group">
  <label>Opinion</label><br>
  <%= f.text_area :body %><br>
   <%= f.submit 'Update Book', class:"btn btn-sm btn-success" %>
<% end %><br>
<%= link_to "Show", book_path(@book.id) %>
|
<a href="/books">Back</a>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<main>
<div class="container">

  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


  <div class="row">
    <div class="col-md-3">
<%= render 'users/list', user: @user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id), method: :get do %>
          <%= image_tag book.user.get_profile_image(100,100) %>
          <% end %>
          <%= link_to book.title , book_path(book.id) %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
  <div>
</div>
</main>

app/views/books/show.html.erb
<main>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
<%= render 'users/list', user: @user, book: @book_new %>
    </div>
    <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id), method: :get do %>
              <%= image_tag @book.user.get_profile_image(100,100) %><br><%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title , book_path(@book.id) %>
            </td>
            <td><%= @book.body %></td>
            <td>
              <% if @user.id == current_user.id %>
              <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success" %>
              <% end %>
            </td>
            <td>
              <% if @user.id == current_user.id %>
              <%= link_to "Destroy", book_path(@book.id), class:"btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に消しますか？" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  <div>
</div>
</main>

app/views/homes/about.html.erb
<h1>welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!</h1>

app/views/homes/top.html.erb
<main>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to<i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In<i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/cccf4986d1.js" crossorigin="anonymous"></script>
  </head>

  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user.id), class: 'nav-link text-light', method: :get do %>
          <i class="fas fa-home"></i>Home<% end %>
          </li>
          <li>
            <a class="nav-link text-light" href="/users">
            <i class="fas fa-users"></i>Users</a>
          </li>
          <li>
            <a class="nav-link text-light" href="/books">
            <i class="fas fa-book-open"></i>Books</a>
          </li>
          <li>
            <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
            <i class="fas fa-sign-out-alt"></i>Log out</a>
          </li>
  　　　　　　　<% else %>
          <li>
            <a class="nav-link text-light" href="/">
            <i class="fas fa-home"></i>Home</a>
          </li>
          <li>
            <a class="nav-link text-light" href="/home/about">
            <i class="fas fa-link"></i>About</a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_up">
            <i class="fas fa-user-plus"></i>Sign up</a>
          </li>
            <a class="nav-link text-light" href="/users/sign_in">
            <i class="fas fa-sign-in-alt"></i>Log in</a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>


  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>

  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
  </footer>
</html>

app/views/users/_list.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100,100) %>
<table class="table">
  <tbody><tr></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</tbody>
</table>

<div class="row">
  <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block", method: :get do %>
  <i class="fas fa-user-cog"></i>
　<% end %>
</div>

<div class="form-group">
  <h2>New book</h2>
  <%= form_with model: book do |f| %><br>
  <label>Title</label><br>
  <%= f.text_field :title %><br>
  <label>Opinion</label><br>
  <%= f.text_area :body %><br>
  <%= f.submit 'Create Book', class:"btn btn-sm btn-success" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>

<%= form_with model: @user, method: :patch do |f| %><br>

  Name<br>

  <%= f.text_field :name %><br>

  Image<br>
  <%= f.file_field :profile_image, accept: "image/*" %><br>

  Introduction<br>

  <%= f.text_field :introduction %><br>

	  <%= f.submit 'Update User', class:"btn btn-sm btn-secondary" %>

<% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<main>
<div class="container">
  <div class="row">
    <div class="col-md-3">
<%= render 'list', user: @user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(100,100) %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
  <div>
</div>
</main>

app/views/users/show.html.erb
<main>
<div class="container">
  <div class="row">
    <div class="col-md-3">
<%= render 'list', user: @user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id), method: :get do %>
          <%= image_tag book.user.get_profile_image(100,100) %>
          <% end %>
        </td>
        <td><%= link_to book.title , book_path(book.id) %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
  <div>
</div>
</main>